### ISSUE TITLE
[Bug] on all tested ISO's, last stream files played the first from list

### ISSUE THREAD

**Issue by AlwinEsch** [xbmc/vfs.sacd#14]
On all ISO's I tested, when the last files were played (swung between 1-4, depending on the ISO), the first file was always played instead, with the title name and text corresponding to the last one.

No idea where the error could be, so here it is deposited that it does not go under.

**Comment by cesarious** [comment]
Just to add details on to this issue.

Platform used for testing. Nvidia Shield TV (2015 - latest firmware). Kodi 19 (alpha, updated 3 days ago). Kodi versions did not change behaviour on this case. 

SACD format: .ISO file. Content in stereo (for some reason, multi channel .ISO do not work for playback).

Ive noticed the issue happens on discs with large quantity of themes (~above 14). In those cases, the list of themes looks complete, but once reached theme 14 (number used just as an example), then theme 1 is playback. And the same is repeated for the remaining themes on the track list.

For some reason this 'critical number' is not consistent. So, i'm in doubt if the issue happens on quantity of themes or begin at certain aggregated duration of the disc.

Tried to change theme list sort, just in case, but did not work.

Thanks in advance, it is a great add-on.

**Comment by AlwinEsch** [comment]
This add is marked from now on as deprecated and it should https://github.com/xbmc/audiodecoder.sacd used instead (allow complete SACD support).

On the other this error not occur.
