### ISSUE TITLE
Cannot read iso SACD 5.1

### ISSUE THREAD

**Issue by glenan** [xbmc/vfs.sacd#23]
In CoreElec/Kodi can read iso files from SACD 2.0 but not  from SACD 5.1.
With 5.1 can hear only a noise.
As already said before : multi channel .ISO do not work for playback only stereo

**Comment by pvanderp** [comment]
SACD ISO files with 6 channel audio support typically contain multiple so called _areas_. It may be that the code is just unable to handle multiple areas. For example, an ISO with two layers with 2 and 6 channel audio will also not play correctly and results in high volume noise on the output.

**Comment by AlwinEsch** [comment]
Have added here a request about https://github.com/xbmc/vfs.sacd/pull/26

Not sure how it come in, maybe there becomes another addon about created, to replace this with them

**Comment by AlwinEsch** [comment]
This add is marked from now on as deprecated and it should https://github.com/xbmc/audiodecoder.sacd used instead (allow complete SACD support).

The SACD 5.1 is now supported on the other, need only a bit improvement about CPU usage by 5.1 streams.
