### ISSUE TITLE
Track metadata not mapped correctly

### ISSUE THREAD

**Issue by pvanderp** [xbmc/vfs.sacd#24]
Songs on an ISO will be sorted by name instead of track. Changing the sort order to "Sort by track" does not work. When you "Sort by file", a numbered sequence of .DSF files is shown:

1.dsf
2.dsf
3.dsf
...

Looks as if the available metadata is not mapped properly. Would be nice to have the tracks sorted by track number by default. That is the intended listening order.

**Comment by AlwinEsch** [comment]
There was a fix about now in Kodi.

This add is marked from now on as deprecated and it should https://github.com/xbmc/audiodecoder.sacd used instead (allow complete SACD support).
