### ISSUE TITLE
ibsacd/common/charset.c:11:19: fatal error: iconv.h: No such file or directory how to fix it on android platform.

### ISSUE THREAD

**Issue by piaozhiye** [xbmc/vfs.sacd#5]
ake[7]: Entering directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/vfs.sacd-prefix/src/vfs.sacd-build'
make[7]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/vfs.sacd-prefix/src/vfs.sacd-build'
make[7]: Entering directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/vfs.sacd-prefix/src/vfs.sacd-build'
[  9%] Building C object lib/libsacd/CMakeFiles/sacd.dir/common/charset.c.o
/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/build/vfs.sacd/lib/libsacd/common/charset.c:11:19: fatal error: iconv.h: No such file or directory
 #include <iconv.h>
                   ^
compilation terminated.
lib/libsacd/CMakeFiles/sacd.dir/build.make:470: recipe for target 'lib/libsacd/CMakeFiles/sacd.dir/common/charset.c.o' failed
make[7]: *** [lib/libsacd/CMakeFiles/sacd.dir/common/charset.c.o] Error 1
make[7]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/vfs.sacd-prefix/src/vfs.sacd-build'
CMakeFiles/Makefile2:210: recipe for target 'lib/libsacd/CMakeFiles/sacd.dir/all' failed
make[6]: *** [lib/libsacd/CMakeFiles/sacd.dir/all] Error 2
make[6]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/vfs.sacd-prefix/src/vfs.sacd-build'
Makefile:127: recipe for target 'all' failed
make[5]: *** [all] Error 2
make[5]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/vfs.sacd-prefix/src/vfs.sacd-build'
CMakeFiles/vfs.sacd.dir/build.make:112: recipe for target 'vfs.sacd-prefix/src/vfs.sacd-stamp/vfs.sacd-build' failed
make[4]: *** [vfs.sacd-prefix/src/vfs.sacd-stamp/vfs.sacd-build] Error 2
make[4]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/vfs.sacd.dir/all' failed
make[3]: *** [CMakeFiles/vfs.sacd.dir/all] Error 2
make[3]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/vfs.sacd.dir/rule' failed
make[2]: *** [CMakeFiles/vfs.sacd.dir/rule] Error 2
make[2]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
Makefile:144: recipe for target 'vfs.sacd' failed
make[1]: *** [vfs.sacd] Error 2
make[1]: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
touch .installed-arm-linux-androideabi-21-debug
make: Leaving directory '/home/piaozhiye/work/xbmc/tools/depends/target/binary-addons'
piaozhiye@ubuntu:~/work/xbmc/tools/depends$

**Comment by notspiff** [comment]
now fixed.
