### ISSUE TITLE
Make a Release

### ISSUE THREAD

**Issue by candrews** [xbmc/vfs.sacd#9]
Can you please make a release?

Thanks!

**Comment by MartijnKaijser** [comment]
Perhaps show some patience while we are working getting everything ready on **all** platforms

**Comment by candrews** [comment]
I'm sorry, I didn't mean to show impatience - it seemed like a reasonable thing to ask for and I thought I did it in a polite way. If you want to contact me and let me know how I can not upset you again, or if there are guidelines I can follow to be better with my communications, I'd be happy to improve myself.

**Comment by MartijnKaijser** [comment]
You didn't really do anything wrong however we are busy with our repo system and it's just that you need to wait a bit

**Comment by Rechi** [comment]
I know we were lazy with tagging versions before, but as we now have a [binary repo](https://kodi.tv/article/kodi-v18-binary-add-ons-repository) for android, osx and windows the situation has improved.
To get new versions published we have to create a git tag, so although your Linux distro won't use the binary repo, you have the benefit that all addons will be correctly tagged.

This addon currently is still WIP and therefore also not available in our binary repo.

**Comment by ArminiusTux** [comment]
@candrews 
You are welcome to follow the [official thread of vfs.sacd on the Kodi forums](https://forum.kodi.tv/showthread.php?tid=106329&page=20). There you can find a link for the compiled addon for LibreELEC Leia. At the moment the addon is working for stereo ISOs but not for 6ch ISOs. I am sure @notspiff is already onto fixing this.

If you really need it asap, I could provide you with a self-compiled vfs.sacd addon for Linux (x86-64) from before the DST decoder was removed. This older version works on all ISOs, but lacks the correct track listing order, the current source offers.

@MartijnKaijser 

> ... we are working getting everything ready on **all** platforms

May I ask, if we can expect a vfs.sacd version for Windows systems then as well?

**Comment by candrews** [comment]
Thanks for the forums link, @ArminiusTux

I'm packaging this (and many other binary add-ons) for Gentoo, so I need a release for my package to be based upon. There's no binary add-ons repo support for Linux (well, except as you pointed out for LibreELEC) so these packages are how Gentoo users get Kodi binary add-ons.

I'll just wait for the release :)

**Comment by ArminiusTux** [comment]
Well that was a quick reply ;-).

So far I have managed to compile the vfs.sacd addon on Ubuntu and macOS 👍 .
All it took was compiling all the addons in advance (incl. Kodi Leia itself) and cmake GUI.

![vfs sacd-cmakegui](https://user-images.githubusercontent.com/44533868/48093561-f8b81300-e20f-11e8-888a-bcecb410badb.PNG)

The screenshot only illustrates the paths to the instruction-files, cmakes expects and which can only be found after an ALL-ADDON compilation. Don't bother to do this on Windows though 👎
